### ISSUE TITLE
Negatives Apply to Whole Expressions

### ISSUE THREAD

**Issue by hakiobo** [cregus/expression-evaluator#2]
https://github.com/cregus/expression-evaluator/blob/5d1993a16fd48ecaba4c35c5cccbd6eb093075c1/src/main/kotlin/pl/kremblewski/expressionevaluator/Tokenizer.kt#L50

By checking for a negative sign like this, expressions like "-5+10" will evaluate to -15 instead of 5

**Comment by cregus** [comment]
Fixed in version 1.0.2. Thanks for this report!
